# Generated by Django 6.0.6 on 2026-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator / Principal'), ('teacher', 'Teacher'), ('student', 'Student / Parent')], default='student', max_length=10),
        ),
    ]
