# Generated by Django 5.2.14 on 2026-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Lớp học'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Đang hoạt động'), (False, 'Đã kết thúc')], default=True, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuition',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Học phí (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả lớp học'),
        ),
    ]
