# Generated by Django 5.2.14 on 2026-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'It's over')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuition',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tuition (VND)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, verbose_name='Class description'),
        ),
    ]
