# Generated by Django 5.2.14 on 2026-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_options_classroom_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Có mặt'), ('absent_excused', 'Vắng (Có phép)'), ('absent_unexcused', 'Vắng (Không phép)'), ('late', 'Đi muộn')], default='present', max_length=20),
        ),
    ]
