# Generated by Django 5.2.14 on 2026-05-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_attendance_remark_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycomment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailycomment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.schedule'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='content',
            field=models.TextField(verbose_name='Nội dung nhận xét'),
        ),
    ]
