# Generated by Django 6.0.6 on 2026-06-28 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhận xét hàng ngày',
                'verbose_name_plural': 'Các nhận xét hàng ngày',
                'db_table': 'Daily_Comments',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mã OTP đặt lại mật khẩu',
                'verbose_name_plural': 'Các mã OTP đặt lại mật khẩu',
                'db_table': 'Password_Reset_OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='Attendances_student_5fc464_idx'),
        ),
        migrations.AddField(
            model_name='dailycomment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_comments', to='core.class'),
        ),
        migrations.AddField(
            model_name='dailycomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_comments', to='core.student'),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailycomment',
            index=models.Index(fields=['student', 'comment_date'], name='Daily_Comme_student_613ccb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycomment',
            unique_together={('student', 'class_obj', 'comment_date')},
        ),
    ]
