# Generated by Django 6.0.6 on 2026-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailycomment_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Giáo viên'), ('student', 'Học sinh')], default='student', max_length=20),
        ),
    ]
