# Generated by Django 6.0.6 on 2026-06-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_classroom_name_alter_classroom_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Điểm danh', 'verbose_name_plural': 'Bảng điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='classenrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Ghi danh', 'verbose_name_plural': 'Danh sách ghi danh'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-id'], 'verbose_name': 'Lớp học', 'verbose_name_plural': 'Danh sách lớp học'},
        ),
        migrations.AlterModelOptions(
            name='dailycomment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Nhận xét hàng ngày', 'verbose_name_plural': 'Nhận xét hàng ngày'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Lịch học', 'verbose_name_plural': 'Lịch học'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Ngày điểm danh'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.schedule', verbose_name='Buổi học'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Có mặt'), ('absent_excused', 'Vắng (Có phép)'), ('absent_unexcused', 'Vắng (Không phép)'), ('late', 'Đi muộn')], db_index=True, default='present', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classrooms.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi danh'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Đang hoạt động'), (False, 'Đã kết thúc')], db_index=True, default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tên lớp'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='date',
            field=models.DateField(db_index=True, null=True, verbose_name='Ngày nhận xét'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.schedule', verbose_name='Buổi học'),
        ),
        migrations.AlterField(
            model_name='dailycomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')], db_index=True, verbose_name='Thứ trong tuần'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phòng học'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
    ]
