# Generated by Django 5.2.14 on 2026-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Tệp đính kèm'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Nội dung yêu cầu'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='Hạn nộp'),
        ),
    ]
