# Generated by Django 5.2.14 on 2026-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_file_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='teacher_feedback',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission file'),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='Teacher feedback'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, verbose_name='Submission content'),
        ),
    ]
