# Generated by Django 6.0.6 on 2026-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_submission_file_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending grading'), ('graded', 'Graded')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
