# Generated by Django 6.0.6 on 2026-06-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission_status'),
        ('classrooms', '0006_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài tập', 'verbose_name_plural': 'Danh sách bài tập'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Bài nộp', 'verbose_name_plural': 'Bài nộp của học sinh'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classrooms.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='Nội dung yêu cầu'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(db_index=True, verbose_name='Hạn nộp'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Tệp đính kèm hướng dẫn'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tiêu đề bài tập'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Bài tập'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='Lời nhắn / Nội dung bài làm'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ chấm'), ('graded', 'Đã có điểm')], db_index=True, default='pending', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian nộp'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Nhận xét của giáo viên'),
        ),
    ]
