# Generated by Django 6.0.6 on 2026-06-25 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_alter_submission_options_and_more'),
        ('classrooms', '0007_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classrooms.classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='Requirement details'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(db_index=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Attached guide file'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Assignment title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='Submission content / Student message'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending grading'), ('graded', 'Graded')], db_index=True, default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submission time'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission file'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Teacher feedback'),
        ),
    ]
